ADCM-8101: refactor startup

diff --git a/os/etc/sv/nginx/run b/os/etc/sv/nginx/run
--- a/os/etc/sv/nginx/run
+++ b/os/etc/sv/nginx/run
@@ -15,15 +15,13 @@
 
 waitforwsgi
 
-if [ -z "$MIGRATION_MODE" ] || [ "$MIGRATION_MODE" -ne 1 ]; then
-    echo "Run Nginx ..."
+echo "Run Nginx ..."
 
-    exec 1>"${adcmlog}/nginx/service_nginx.out"
-    exec 2>"${adcmlog}/nginx/service_nginx.err"
+exec 1>"${adcmlog}/nginx/service_nginx.out"
+exec 2>"${adcmlog}/nginx/service_nginx.err"
 
-    # Cleanup tmp dir during restart of nginx.
-    # That dir is for uploading bundles cache.
-    # This is for old existing installations
-    rm -rf  ${adcmtmp}/nginx_client_temp || true
-    exec /usr/sbin/nginx -c /etc/nginx/nginx.conf  -g "daemon off;"
-fi
+# Cleanup tmp dir during restart of nginx.
+# That dir is for uploading bundles cache.
+# This is for old existing installations
+rm -rf ${adcmtmp}/nginx_client_temp || true
+exec /usr/sbin/nginx -c /etc/nginx/nginx.conf  -g "daemon off;"
